---

name: CI

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'feature/**'
    #branches-ignore:
    #  - '**'
    #tags:
    #  - '*.*.*'
  schedule:
    - cron: "0 20 * * 0"

jobs:
  release-linux-amd64:
    name: "release with go version: ${{ matrix.go }}"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        release_tag:
          - "0.10.2"
        go:
          - "1.22"

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "build release ${{ matrix.release_tag }}"
        uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.GH_REGISTRY_TOKEN }}
          release_tag: ${{ matrix.release_tag }}
          goos: linux
          goarch: amd64
          goversion: ${{ matrix.go }}
          binary_name: registry-ui
          sha256sum: true
          overwrite: true
          extra_files: LICENSE README.md templates static
